name: 'DAG integration check'
description: 'Run some testing on a DAG definition'

inputs:
  DAG:  
    description: 'DAG folder name'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DAG }}