name: Nightly backup build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
    
jobs:
  backup:
    name: Create nightly backup
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Define dynamic env variables
        run: echo "FILENAME="$(date +'%Y%m%d') >> $GITHUB_ENV
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILENAME }}
          path: |
            *
            !.git
          retention-days: 3
