name: DAGs integration testing
on:
  pull_request:
    branches:
      - main
    
jobs:
  check_pull_request:
    name: Test before integration
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Define fynamic env variables
        run: |
          echo "BRANCH"=${GITHUB_HEAD_REF##*/} >> $GITHUB_ENV
      -
        name: DAG testing on airflow environment
        uses: ./.github/actions/airflow
        with:
          dag_folder: ${{ env.BRANCH }}
#     - 
#       name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.6
#     -
#       name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install apache-airflow==1.10.10
#     -
#       name: Lint with flake8
#       working-directory: ${{ env.BRANCH }}
#       run: |
#         pip install flake8
#         flake8
#     -
#       name: Test with pytest
#       working-directory: ${{ env.BRANCH }}
#       run: |
#         pip install pytest
#         pytest
#     -
#       name: Test with airflow's dagbag
#       env:
#         BRANCH: ${{ env.BRANCH }}
#       shell: python
#       run: |
#         import os
#         from airflow.models import DagBag
#         bag = DagBag(dag_folder=".", include_examples=False)
#         if bag.import_errors or not bag.dags:
#           raise ValueError(bag.import_errors)
