name: DAGs integration testing
on:

  pull_request:
    branches:
      - main
    
jobs:

  testing_and_linting:
    name: Run unit testing and linting
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v2
      -
        name: Define dynamic variables
        run: |
          echo "BRANCH"=${GITHUB_HEAD_REF##*/} >> $GITHUB_ENV
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      -
        name: Unit testing
        run: |
          if [ -d ${{ env.BRANCH }}/tests/ ]; then
            pytest;
          fi
        
  dag_integration:
    name: Test DAG integration
    runs-on: ubuntu-latest
    needs: testing_and_linting
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v2
      -
        name: Define dynamic variables
        run: |
          echo "BRANCH"=${GITHUB_HEAD_REF##*/} >> $GITHUB_ENV
      -
        name: DAG testing on airflow environment
        uses: ./.github/actions/airflow
        with:
          DAG: ${{ env.BRANCH }}
