name: DAGs integration testing
on:
  pull_request:
    branches:
      - main
    
jobs:
  check_pull_request:
    name: Test before integration
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Define fynamic env variables
        run: |
          echo "BRANCH"=${GITHUB_HEAD_REF##*/} >> $GITHUB_ENV
      -
        name: DAG testing on airflow environment
        uses: ./.github/actions/airflow
        with:
          dag_folder: ${{ env.BRANCH }}
